apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.pikafishengine'
version = '1.0.0'

android {
  namespace "expo.modules.pikafishengine"
  compileSdkVersion safeExtGet("compileSdkVersion", 35)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
    consumerProguardFiles 'proguard-rules.pro'
  }

  sourceSets {
    main {
      jniLibs.srcDirs = ['src/main/jniLibs']
      assets.srcDirs = ['src/main/assets']
    }
  }

  lintOptions {
    abortOnError false
  }

  publishing {
    singleVariant("release") {
      withSourcesJar()
    }
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${getKotlinVersion()}"
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

def getKotlinVersion() {
  def kotlinVersion = rootProject.ext.has("kotlinVersion")
    ? rootProject.ext.get("kotlinVersion")
    : "2.0.21"
  return kotlinVersion
}
